copy-left:
  "Andreas Schempp <andreas.schempp@terminal42.ch>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
    - "Polyfill45/Asset/ContaoContext.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPass.php"
    - "Polyfill45/EventListener/InsertTags/AssetListener.php"
    - "Polyfill45/EventListener/InsertTags/AssetListenerTest.php"
    - "Polyfill45/Util/PackageUtil.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPassTest.php"
    - "Polyfill45/Asset/ContaoContextTest.php"
  "David Molineus <mail@netzmacht.de>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
  "Leo Feyer <github@contao.org>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
    - "Polyfill45/Asset/ContaoContext.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPass.php"
    - "Polyfill45/EventListener/InsertTags/AssetListener.php"
    - "Polyfill45/EventListener/InsertTags/AssetListenerTest.php"
    - "Polyfill45/Util/PackageUtil.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPassTest.php"
    - "Polyfill45/Asset/ContaoContextTest.php"
    - "Polyfill48/Database/Installer.php"
    - "Polyfill48/Database/MigrationInstaller.php"
  "Martin Auswöger <martin@auswoeger.com>":
    - "Polyfill48/Command/MigrateCommand.php"
    - "Polyfill48/Database/Installer.php"
    - "Polyfill48/DependencyInjection/Compiler/TaggedMigrationsPass.php"
    - "Polyfill48/Migration/MigrationCollection.php"
    - "Polyfill48/Migration/MigrationInterface.php"
    - "Polyfill48/Migration/MigrationResult.php"
    - "Polyfill48/Fixtures/AbstractMigration.php"
    - "Polyfill48/Database/MigrationInstaller.php"
    - "Polyfill48/Migration/MigrationCollectionPolyFill.php"
    - "Polyfill48/Migration/MigrationInterfacePolyFill.php"
    - "Polyfill48/Migration/MigrationResultPolyFill.php"
