copy-left:
  "Andreas Schempp <andreas.schempp@terminal42.ch>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
    - "Polyfill45/Asset/ContaoContext.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPass.php"
    - "Polyfill45/EventListener/InsertTags/AssetListener.php"
    - "Polyfill45/EventListener/InsertTags/AssetListenerTest.php"
    - "Util/PackageUtil.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPassTest.php"
    - "Polyfill45/Asset/ContaoContextTest.php"
  "David Molineus <mail@netzmacht.de>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
  "Leo Feyer <github@contao.org>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
    - "Polyfill45/Asset/ContaoContext.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPass.php"
    - "Polyfill45/EventListener/InsertTags/AssetListener.php"
    - "Polyfill45/EventListener/InsertTags/AssetListenerTest.php"
    - "Util/PackageUtil.php"
    - "Polyfill45/DependencyInjection/Compiler/AddAssetsPackagesPassTest.php"
    - "Polyfill45/Asset/ContaoContextTest.php"
    - "Polyfill49/Database/Installer.php"
    - "Polyfill49/Database/MigrationInstaller.php"
  "Martin Auswöger <martin@auswoeger.com>":
    - "Polyfill49/Command/MigrateCommand.php"
    - "Polyfill49/Database/Installer.php"
    - "Polyfill49/DependencyInjection/Compiler/TaggedMigrationsPass.php"
    - "Polyfill49/Migration/MigrationCollection.php"
    - "Polyfill49/Migration/MigrationInterface.php"
    - "Polyfill49/Migration/MigrationResult.php"
    - "Polyfill49/Fixtures/AbstractMigration.php"
    - "Polyfill49/Database/MigrationInstaller.php"
    - "Polyfill49/Migration/MigrationCollectionPolyFill.php"
    - "Polyfill49/Migration/MigrationInterfacePolyFill.php"
    - "Polyfill49/Migration/MigrationResultPolyFill.php"
