copy-left:
  "Andreas Schempp <andreas.schempp@terminal42.ch>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
  "David Molineus <mail@netzmacht.de>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
  "Leo Feyer <github@contao.org>":
    - "Polyfill45/Initialization/HookListenerRegistrar.php"
    - "Polyfill45/Initialization/HookListenerRegistrarTest.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPass.php"
    - "Polyfill45/DependencyInjection/Compiler/RegisterHookListenersPassTest.php"
